services:
  auth-service:
    build: ./authentication
    container_name: auth-service
    ports:
      - "3001:3001"
    depends_on:
      - auth-db
    environment:
      - PORT=3001
      - DB_HOST=auth-db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=auth_db
      - JWT_SECRET=your_jwt_secret_key
    networks:
      - ecommerce-network
    restart: unless-stopped

  auth-db:
    image: mysql:8.0
    container_name: auth-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=auth_db
    volumes:
      - auth-db-data:/var/lib/mysql
      - ./authentication/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - ecommerce-network
    restart: unless-stopped
    
  catalog-service:
    build: ./catalog
    container_name: catalog-service
    ports:
      - "3002:3002"
    depends_on:
      - catalog-db
    environment:
      - PORT=3002
      - DB_HOST=catalog-db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=catalog_db
      - JWT_SECRET=your_jwt_secret_key
    networks:
      - ecommerce-network
    restart: unless-stopped
    
  catalog-db:
    image: mysql:8.0
    container_name: catalog-db
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=catalog_db
    volumes:
      - catalog-db-data:/var/lib/mysql
      - ./catalog/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - ecommerce-network
    restart: unless-stopped
  
  frontend:
    build: ./frontend
    container_name: frontend-service
    ports:
      - "80:80"
    networks:
      - ecommerce-network
    depends_on:
      - catalog-service
      - auth-service
    restart: unless-stopped
  
  payment-service:
    build: ./paymentService
    container_name: payment-service
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - SUCCESS_URL=http://localhost:80/success.html
      - CANCEL_URL=http://localhost/stripe/cancel.html
    networks:
      - ecommerce-network
    restart: unless-stopped

networks:
  ecommerce-network:
    driver: bridge

volumes:
  auth-db-data:
  catalog-db-data:
