apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-deployment
  labels:
    app: support-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: support-service
  template:
    metadata:
      labels:
        app: support-service
    spec:
      containers:
      - name: support-service
        image: fynewix/support-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3004
        envFrom:
        - configMapRef:
            name: env-config
        env:
        - name: SUPPORT_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-auth-secret
              key: mysql-root-password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret
        readinessProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"