apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-service
spec:
  replicas: 1  # You can scale this number as per your needs
  selector:
    matchLabels:
      app: support-service
  template:
    metadata:
      labels:
        app: support-service
    spec:
      containers:
        - name: support-service
          image: your-dockerhub-username/support-service:latest  # Replace with actual image
          ports:
            - containerPort: 3004
          env:
            - name: DB_HOST
              value: support-db
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: support-secrets
                  key: db_password
            - name: DB_NAME
              value: support_db
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: support-secrets
                  key: jwt_secret
          restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: support-service
spec:
  ports:
    - port: 3004
      targetPort: 3004
  selector:
    app: support-service
  type: ClusterIP  # You can change it to NodePort or LoadBalancer for external access
