apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: support-mysql
spec:
  selector:
    matchLabels:
      app: support-mysql
  serviceName: "support-db"
  replicas: 1
  template:
    metadata:
      labels:
        app: support-mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-auth-secret
              key: mysql-root-password
        - name: MYSQL_DATABASE
          value: support_db
        volumeMounts:
        - name: support-mysql-data
          mountPath: /var/lib/mysql
        - name: support-initdb
          mountPath: /docker-entrypoint-initdb.d
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
      volumes:
      - name: support-initdb
        configMap:
          name: support-mysql-initdb
  volumeClaimTemplates:
  - metadata:
      name: support-mysql-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: support-db
spec:
  selector:
    app: support-mysql
  ports:
  - port: 3306
    targetPort: 3306
  clusterIP: None