apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # Facultatif, Kubernetes attribue un port aléatoire si non spécifié
  selector:
    app: frontend
