apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - port: 3001
    targetPort: 3001
    nodePort: 31001 # Ajoute cette ligne avec un port libre (31001)
  type: NodePort