apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  selector:
    app: catalog-service
  ports:
  - port: 3002
    targetPort: 3002
    nodePort: 31002 # Ajoute cette ligne avec un port libre (31001)
  type: NodePort