apiVersion: v1
kind: Secret
metadata:
  name: mysql-auth-secret
type: Opaque
data:
  mysql-root-password: cGFzc3dvcmQ=  # 'password' encodé en base64
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  secret: eW91cl9qd3Rfc2VjcmV0X2tleQ==  # 'your_jwt_secret_key' encodé en base64